Improve match pattern in replaceCurrentUrlLanguage
spryker-shop/language-switcher-widget pull request #1
Opened 2022-08-04 08:00 UTC by victor-ufg

We were having a problem in the widget where when there was no ending /, the language switcher would redirect to a 404 non existing page.
For example, when in /de and switching from German to French or Italian, the switcher would output links to /fr/de or /it/de respectively.

The new regex matches /de or /de/ in-distinctively, from the beginning of the url path.

2022-08-10 15:08 UTC, dereuromark commented
In the meantime, please check that:
- Your code is free of side effects that could harm other use cases
- Your code is tested, ideally a small test case provided along side the change to show the issue is indeed fixed

With this we can process it much faster and will be able to deliver the fixed module(s) to you with highest quality.

2022-10-05 15:23 UTC, yaroslav-spryker requested changes

2022-10-05 15:23 UTC, yaroslav-spryker commented on src/SprykerShop/Yves/LanguageSwitcherWidget/Widget/LanguageSwitcherWidget.php
> +        if (preg_match('~^/(' . implode('|', $languages) . ')/?~', $currentUrl)) {
@victor-ufg Could you please add test for the updated regular expression?
Ideally it should be two tests: for old non-working(incorrectly worked) one and for new one. Say positive and negative tests.

2023-11-28 09:19 UTC, valerio8787 commented
Dear @victor-ufg,

We want to express our appreciation for your recent contribution to our project.

Your pull request has been reviewed and it is closed because the behavior you described could not be reproduced.

Thanks again for your contribution and we are looking forward to seeing your contribution soon!

Best,
Spryker Team

2023-11-28 09:19 UTC, closed without merging